### PR TITLE
add support for INSR status register to DG645

### PR DESCRIPTION
**Pull request by runchman**
Added a db record and support in drvAsynDG645.cpp for the INSR? command that returns the event status register on the DG645

### CODE REVIEW

**Comment by dohnarms** [comment]
I'm going to add a change after the merge to make the record name $(P)$(R)EventStatusLI (adding LI at the end), to be consistent with the naming convention started by the original author.

**Comment by anjohnson** [comment]
Hi @dohnarms, thanks for merging this so quickly. Any chance you're planning to tag a release of the module any time soon? John @runchman wants to use a version of delaygen that includes this PR in his IOC soon, and I prefer to import tagged module versions into the Controls C2 area if possible, although I can use a commit SHA if not.

Thanks,

- Andrew

**Comment by dohnarms** [comment]
Hi @anjohnson ,
I want to get the new PV on the DG645 screen so it's easy to find.  I'll see if I can make a release today.
Dohn

**Comment by dohnarms** [comment]
Hi @runchman , I added an mbbiDirect version of the new PV (ending in MBBID), so that I can access the individual bits for a new screen that shows the status of each bit.  I think you can treat the VAL field of the MBBID version the same as as the VAL field from the LI version of the PV.  Do you need a separate longin version if this mbbiDirect PV exists?
Dohn

**Comment by runchman** [comment]
Mbbi record alone is just fine, thanks!

**Comment by dohnarms** [comment]
Hi @runchman , I left the longin, which now feeds the mbbiDirect, as supporting the mbbiDirect with the driver was not trivial.
The new screen uses the mbbiDirect to break out the bits easily.

Anyway, I just made a release, @anjohnson

**Pull request merged**
